source = '../../lib/implot/implot.h'
target = 'src/aimplot/bindings/generated.cpp'

prefix = 'ImPlot'
short_prefix = 'Im'

module = '_aimplot'

flags = [
    '-std=c++17',
    '-DIMGUI_DISABLE_OBSOLETE_FUNCTIONS=1',
    '-DIMPLOT_DISABLE_OBSOLETE_FUNCTIONS=1',
    '-I../../lib/imgui'
]

excludes = [
    # Wrapped
    'ImPlot::CreateContext',
    'ImPlot::DestroyContext',
    'ImPlot::GetCurrentContext',
    'ImPlot::SetCurrentContext',
    # Internal / Ignored
    'ImPlotLimits::Contains',
    'ImPlot::PixelsToPlot',
    'ImPlot::SetNextPlotTicksX',
    'ImPlot::SetNextPlotTicksY',
    'ImPlotRect::Contains', #TODO: overload problems
    'ImPlot::SetupAxisTicks' #TODO: generator problem:
        #_aimplot.def("setup_axis_ticks", py::overload_cast<ImAxis, double, double, int, const char *const [], bool>(&ImPlot::SetupAxisTicks)
    #Obsolete
]

overloaded = [
    'ImPlot::LerpColormap'
]
