excludes = [
    # Wrapped
    'ImGui::Combo',
    'ImGui::MenuItem',
    'ImGui::Selectable',
    'ImGui::ListBox',
    'ImGui::InputText',
    'ImGui::InputTextMultiline',
    'ImGui::CollapsingHeader',
    'ImGui::PlotLines',
    'ImGui::PlotHistogram',
    'ImDrawData::CmdLists',
    'ImGuiIO::MouseDown',
    'ImGuiIO::KeysDown',
    'ImGuiIO::KeyMap',
    'ImGuiIO::InputCharacters',
    'ImGuiIO::NavInputs',
    'ImFontAtlas::GetTexDataAsAlpha8',
    'ImFontAtlas::GetTexDataAsRGBA32',

    # Internal / Ignored
    'ImGuiTextFilter::Filters',
    'ImGuiStorage::Data',
    'ImFontAtlas::TexPixelsAlpha8',
    'ImFontAtlas::TexPixelsRGBA32',
    'ImFontAtlas::TexWidth',
    'ImFontAtlas::TexHeight',
    'ImFontAtlas::TexUvScale',
    'ImFontAtlas::TexUvWhitePixel',
    'ImFontAtlas::Fonts',
    'ImFontAtlas::CustomRects',
    'ImFontAtlas::ConfigData',
    'ImFontAtlas::CustomRectIds',
    'ImFontAtlas::AddCustomRectRegular',
    'ImFontAtlas::AddCustomRectFontGlyph',
    'ImFontAtlas::GetCustomRectByIndex',
    'ImFontAtlas::CalcCustomRectUV',
    'ImFontAtlas::GetMouseCursorTexData',
    'ImFontGlyph::Codepoint',
    'ImFontGlyph::Visible',
    'ImFont::CalcTextSizeA',
    'ImGui::SetNextWindowSizeConstraints',
    'ImGui::SetAllocatorFunctions',
    'ImGui::MemAlloc',
    'ImGui::MemFree',
    'ImGuiIO::GetClipboardTextFn',
    'ImGuiIO::SetClipboardTextFn',
    'ImGuiIO::ImeSetInputScreenPosFn',
    'ImDrawCmd::UserCallback',
    'ImColor::HSV',
    'ImNewDummy',
    'ImGuiTextBuffer',
    'CustomRect',
    'ImGui',
    'ImGuiPlatformIO',
    'ImGuiPlatformMonitor',
    'ImGuiDockContext',
    'ImGuiDockNodeSettings',
    'ImGuiListClipper'
]

overloaded = [
    'ImGui::IsPopupOpen',
    'ImGui::SetScrollX',
    'ImGui::SetScrollY',
    'ImGui::SetScrollFromPosX',
    'ImGui::SetScrollFromPosY'
]
