source = '../../lib/imgui/imgui.h'
target = 'src/aimgui/bindings/generated.cpp'

prefix = 'ImGui'
short_prefix = 'Im'

module = '_aimgui'

flags = [
    '-x',
    'c++',
    '-std=c++17',
    '-DIMGUI_DISABLE_OBSOLETE_FUNCTIONS=1',
    '-DIMGUI_DISABLE_OBSOLETE_KEYIO=1'
]

excludes = [
    # Wrapped
    'ImGui::CreateContext',
    'ImGui::DestroyContext',
    'ImGui::GetCurrentContext',
    'ImGui::SetCurrentContext',
    #'ImGui::BeginPopupModal',
    'ImGui::SetDragDropPayload',
    'ImGui::Combo',
    'ImGui::MenuItem',
    'ImGui::Selectable',
    'ImGui::ListBox',
    'ImGui::InputText',
    'ImGui::InputTextMultiline',
    'ImGui::CollapsingHeader',
    'ImGui::PlotLines',
    'ImGui::PlotHistogram',
    'ImDrawData::CmdLists',
    'ImDrawList::AddPolyline',
    'ImGuiIO::MouseDown',
    'ImGuiIO::KeysDown',
    'ImGuiIO::KeyMap',
    'ImGuiIO::InputCharacters',
    'ImGuiIO::NavInputs',
    'ImFontAtlas::AddFontFromFileTTF',
    'ImFontAtlas::GetTexDataAsAlpha8',
    'ImFontAtlas::GetTexDataAsRGBA32',
    'ImGuiStyle::Colors',

    # Internal / Ignored
    'ImGui::TableGetColumnName', #TODO:Wrap or something
    'ImGuiTableColumnSortSpecs::SortDirection',
    'ImFontGlyph::Colored',
    'ImGui::GetAllocatorFunctions',
    'ImGuiTextFilter::Filters',
    'ImGuiStorage::Data',
    'ImFontAtlas::TexPixelsAlpha8',
    'ImFontAtlas::TexPixelsRGBA32',
    'ImFontAtlas::TexWidth',
    'ImFontAtlas::TexHeight',
    'ImFontAtlas::TexUvScale',
    'ImFontAtlas::TexUvWhitePixel',
    'ImFontAtlas::Fonts',
    'ImFontAtlas::CustomRects',
    'ImFontAtlas::ConfigData',
    'ImFontAtlas::CustomRectIds',
    'ImFontAtlas::AddCustomRectRegular',
    'ImFontAtlas::AddCustomRectFontGlyph',
    'ImFontAtlas::GetCustomRectByIndex',
    'ImFontAtlas::CalcCustomRectUV',
    'ImFontAtlas::GetMouseCursorTexData',
    'ImFontGlyph::Codepoint',
    'ImFontGlyph::Visible',
    'ImFont::CalcTextSizeA',
    'ImGui::SetNextWindowSizeConstraints',
    'ImGui::SetAllocatorFunctions',
    'ImGui::MemAlloc',
    'ImGui::MemFree',
    'ImGuiIO::GetClipboardTextFn',
    'ImGuiIO::SetClipboardTextFn',
    'ImGuiIO::ImeSetInputScreenPosFn',
    'ImDrawCmd::UserCallback',
    'ImColor::HSV',
    'ImNewDummy',
    #TODO:Is this causing the link error? ImGuiTextBuffer::EmptyString
    'ImGuiTextBuffer',
    'CustomRect',
    'ImGuiPlatformIO',
    'ImGuiPlatformMonitor',
    'ImGuiDockContext',
    'ImGuiDockNodeSettings',
    'ImGuiListClipper',
    'ImGuiContext',

    #Obsolete
    'ImGuiIO::RenderDrawListsFnUnused'
]

overloaded = [
    'ImGui::IsPopupOpen',
    'ImGui::SetScrollX',
    'ImGui::SetScrollY',
    'ImGui::SetScrollFromPosX',
    'ImGui::SetScrollFromPosY',
    'ImGui::IsKeyDown',
    'ImGui::IsKeyPressed',
    'ImGui::IsKeyReleased',
    'ImGui::IsMouseDown',
    'ImGui::IsMouseClicked',
    'ImGui::IsMouseReleased'
]

[defaults]
    'out_h' = '0'
    'out_s' = '0'
    'out_v' = '0'
    'out_r' = '0'
    'out_g' = '0'
    'out_b' = '0'
    'out_ini_size' = '0'

