source = '../bgfx/include/bgfx/bgfx.h'
mapped = 'bgfx.h'
target = 'src/aimgfx/bindings/bgfx.cpp'

prefix = ''
short_prefix = ''

module = 'libaimgfx'

# Flags that get passed to LLVM to parse the headers
flags = [
    '-std=c++17',
    #'-DIMGUI_DISABLE_OBSOLETE_FUNCTIONS=1',
    '-I../bgfx/include'
]

excludes = [
    # Problems
    'bgfx::VertexLayout::decode',
    'bgfx::setPaletteColor',
    'bgfx::topologySortTriList',
    'bgfx::vertexPack' #deleted function?
    # Wrapped
    # Internal / Ignored
    #Obsolete
]

overloaded = [
]

[defaults]
'_layoutHandle' = 'bgfx::VertexLayoutHandle(BGFX_INVALID_HANDLE)'
'_init' = 'bgfx::Init()'


