source = '../bgfx/include/bgfx/platform.h'
#TODO: Might want multiple, mappable headers
mapped = 'platform.h'
target = 'src/aimgfx/bindings/platform.cpp'

prefix = ''
short_prefix = ''

module = 'libaimgfx'

# Flags that get passed to LLVM to parse the headers
flags = [
    '-std=c++17',
    #'-DIMGUI_DISABLE_OBSOLETE_FUNCTIONS=1',
    '-I../bgfx/include'
]

excludes = [
    # Problems
    # Wrapped
    # Internal / Ignored
    #Obsolete
]

overloaded = [
]
