source = '../implot/implot.h'
target = 'src/aimplot/bindings/generated.cpp'

flags = [
    '-std=c++17',
    '-DIMGUI_DISABLE_OBSOLETE_FUNCTIONS=1'
]

excludes = [
    # Wrapped
    # Internal / Ignored
    'ImPlotLimits::Contains',
    'ImPlot::PixelsToPlot',
    'ImPlot::SetNextPlotTicksX',
    'ImPlot::SetNextPlotTicksY',
    #Obsolete
]

overloaded = [
    'ImPlot::LerpColormap'
]
