source = '../../lib/bgfx/include/bgfx/bgfx.h'
target = 'src/aimgfx/bindings/bgfx.cpp'

module = 'libaimgfx'

# Flags that get passed to LLVM to parse the headers
flags = [
    '-std=c++17',
    '-I../../lib/bgfx/include'
]

excludes = [
    # Problems
    'bgfx::VertexLayout::decode', # error C2352: 'bgfx::VertexLayout::decode': illegal call of non-static member function
    'bgfx::setPaletteColor',
    'bgfx::topologySortTriList',
    'bgfx::vertexPack' #deleted function?
    # Wrapped
    # Internal / Ignored
    #Obsolete
]

overloaded = [
]

[defaults]
'_layoutHandle' = 'bgfx::VertexLayoutHandle(BGFX_INVALID_HANDLE)'
'_init' = 'bgfx::Init()'


