source = '../../lib/bgfx/include/bgfx/embedded_shader.h'
target = 'src/aimgfx/bindings/embedded_shader.cpp'

module = 'libaimgfx'

# Flags that get passed to LLVM to parse the headers
flags = [
    '-std=c++17',
    '-I../../lib/bgfx/include'
]

excludes = [
    # Problems
    # Wrapped
    # Internal / Ignored
    #Obsolete
]

overloaded = [
]
