source = '../bgfx/include/bgfx/platform.h'
target = 'src/aimgfx/bindings/platform.cpp'

module = 'libaimgfx'

# Flags that get passed to LLVM to parse the headers
flags = [
    '-std=c++17',
    '-I../bgfx/include'
]

excludes = [
    # Problems
    # Wrapped
    # Internal / Ignored
    #Obsolete
]

overloaded = [
]
