source = '../bgfx/include/bgfx/bgfx.h'
#TODO: Might want multiple, mappable headers
mapped = 'bgfx.h'
target = 'src/aimgfx/bindings/generated.cpp'

prefix = ''
short_prefix = ''

module = 'libaimgfx'

# Flags that get passed to LLVM to parse the headers
flags = [
    '-std=c++17',
    #'-DIMGUI_DISABLE_OBSOLETE_FUNCTIONS=1',
    '-I../bgfx/include'
]

excludes = [
    # Problems
    'bgfx::VertexLayout::decode',
    'bgfx::setPaletteColor',
    'bgfx::topologySortTriList',
    'bgfx::vertexPack' #deleted function?
    # Wrapped
    # Internal / Ignored
    #Obsolete
]

overloaded = [
]
