source = '../bgfx/include/bgfx/bgfx.h'
#TODO: Might want multiple, mappable headers
mapped = 'bgfx.h'
target = 'src/aimgfx/bindings/generated.cpp'

prefix = ''
short_prefix = ''

module = 'libaimgfx'

flags = [
    '-std=c++17',
    '-DIMGUI_DISABLE_OBSOLETE_FUNCTIONS=1',
    '-I../imgui'
]

excludes = [
    # Wrapped
    # Internal / Ignored
    #Obsolete
]

overloaded = [
]
