source = '../imnodes/imnodes.h'
target = 'src/aimnodes/bindings/generated.cpp'

flags = [
    '-std=c++17',
    '-DIMGUI_DISABLE_OBSOLETE_FUNCTIONS=1',
    '-I../imgui'
]

excludes = [
    # Wrapped
    'ImNodes::CreateContext',
    'ImNodes::DestroyContext',
    'ImNodes::GetCurrentContext',
    'ImNodes::SetCurrentContext',

    'ImNodes::EditorContextCreate',
    'ImNodes::EditorContextFree',
    'ImNodes::EditorContextSet',
    # Internal / Ignored
    'ImNodes::EditorContext',
    'ImNodes::SaveEditorStateToIniString',
    'ImNodes::LoadEditorStateFromIniFile',
    'ImNodes::LoadEditorStateFromIniString',
    'ImNodes::SaveEditorStateToIniFile',
    #Obsolete
]

overloaded = [
]
