source = '../implot/implot.h'
mapped = 'implot.h'
target = 'src/aimplot/bindings/generated.cpp'

prefix = 'ImPlot'
short_prefix = 'Im'

module = 'libaimplot'

flags = [
    '-std=c++17',
    '-DIMGUI_DISABLE_OBSOLETE_FUNCTIONS=1',
    '-I../imgui'
]

excludes = [
    # Wrapped
    'ImPlot::CreateContext',
    'ImPlot::DestroyContext',
    'ImPlot::GetCurrentContext',
    'ImPlot::SetCurrentContext',
    # Internal / Ignored
    'ImPlotLimits::Contains',
    'ImPlot::PixelsToPlot',
    'ImPlot::SetNextPlotTicksX',
    'ImPlot::SetNextPlotTicksY',
    #Obsolete
]

overloaded = [
    'ImPlot::LerpColormap'
]
