[tool.poetry]
name = "aimplotdemo"
version = "0.1.0"
description = ""
authors = ["Kurtis Fields <kurtisfields@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
arcade = "^2.6.16"
numpy = "^1.21.2"
aimgui = {path = "../aimgui",  develop = true}
aimplot = {path = "../aimplot",  develop = true}

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
