source = '../glfw/include/GLFW/glfw3.h'
target = 'src/aimapp/bindings/glfw.cpp'

module = 'libaimapp'

flags = [
    '-std=c++17',
    '-I../glfw/include'
]

excludes = [
    # Wrapped
    # Internal / Ignored
    'glfwGetProcAddress',
    'glfwGetRequiredInstanceExtensions'
    # Obsolete
]

overloaded = [
]
